In [2]:
print "hey boy"

hey boy


In [3]:
print "short"

short


In [4]:
import numpy as np

In [5]:
np

<module 'numpy' from '/usr/local/lib/python2.7/site-packages/numpy/__init__.pyc'>

In [6]:
a = np.array([0, 1, 2, 3])


In [7]:
a

array([0, 1, 2, 3])

In [8]:
b = np.array([[0, 1, 2], [3, 4, 5]])

In [9]:
b.shape

(2, 3)

In [10]:
x = np.empty()
x

TypeError: Required argument 'shape' (pos 1) not found

In [11]:
x = np.empty((5,5))

In [12]:
x

array([[ -3.10503618e+231,   1.73060419e-077,   2.18620353e-314,
          2.20064140e-314,   2.18675793e-314],
       [  2.20064062e-314,   2.18621072e-314,   2.20064128e-314,
          2.18675793e-314,   2.20064076e-314],
       [  2.18621072e-314,   2.20064137e-314,   2.18675793e-314,
          2.20064123e-314,   2.18621072e-314],
       [  2.20064116e-314,   2.18675793e-314,   2.20064102e-314,
          2.18621072e-314,   2.20064126e-314],
       [  2.18675793e-314,   2.20064104e-314,   2.18621072e-314,
          2.20064121e-314,   2.18642710e-314]])

In [13]:
xx = np.array(np.random.rand(4), np.random.rand(4))

TypeError: data type not understood

In [14]:
y = np.random.rand(4)

In [15]:
z = np.random.rand(4)

In [16]:
a = np.array([y,z])

In [17]:
a

array([[ 0.51628419,  0.09509743,  0.7455332 ,  0.17707446],
       [ 0.09995979,  0.06629478,  0.07977815,  0.93794997]])